staging:
  type: deploy
  image: ruby:2.3
  script:
    - apt-get update -qy
    - apt-get install -yqq ruby ruby-dev nodejs --silent
    - gem install dpl
    - echo '$HEROKU_APP_NAME $HEROKU_STAGING_API_KEY'
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_STAGING_API_KEY
#  when: manual
  only:
    - master
    - develop

